---
- hosts: Metro_NXOS
  gather_facts: false
  connection: network_cli
  vars:
#    - ansible_port: "{{ ssh_port }}"
    - ansible_network_os: "{{ network_os }}"
    - ssh_debug: "{{ ansible_ssh_common_args }}"

  tasks:
  - name: Backup Config
    nxos_config:
      backup: yes
      backup_options:
        filename: "{{ hostname }}"
        dir_path: /etc/ansible/backups
      #check_mode: yes
