
---
- hosts: Metro_Proxy
  #hosts: 10.0.0.250
  gather_facts: false
  connection: network_cli
  vars:
    - ansible_port: "{{ ssh_port }}"
    - ansible_network_os: "{{ network_os }}"
    - ssh_debug: "{{ ansible_ssh_common_args }}"

  tasks:
  - name: configurable backup path
    nxos_config:
      backup: yes
      backup_options:
        filename: nxos-test.cfg
        dir_path: /etc/ansible/backups
