---
- name: Update Adtran syslog
  cli_config:
    config: logging forwarding receiver-ip {{ item.name }}
  with_items:
    - "{{ system['syslog']['hosts'] }}"

- name: Update Adtran ntp
  cli_config:
    config: ntp server {{ item.ntp_server }}
  with_items:
    - "{{ system['ntp']['hosts'] }}"
