---
## Update cisco devices syslogs.
- name: Update Syslog
  cisco.ios.ios_config:
    src: syslog-cisco.j2
  tags:
    - syslog

## Update Cisco NTP.
- name: Update NTP Cisco
  cisco.ios.ios_ntp:
    server: "{{ item.ntp_server }}"
    state: present
  with_items:
    - "{{ system['settings']['ntp'] }}"