---
- hosts: testing
  gather_facts: no
  connection: local

  tasks:
    - import_role:
        name: system
    - import_role:
        name: snmp
    - import_role:
        name: aaa
    - import_role:
        name: security