---
  - name: Generate Host Specific Static Routes
    template:
      src: routing-statics.j2
      dest: /templates/adtran/{{inventory_hostname}}_static_routes.text

  - name: Generate Host Specific BGP Config
    template:
      src: routing-bgp.j2
      dest: /templates/adtran/{{inventory_hostname}}_bgp_config.text