---
- hosts: testing
#  roles:
#    - ios.ios
  gather_facts: false
  #connection: local
  #connection: netconf
  connection: network_cli
  tasks:
    ## This pulls settings from /etc/ansible/group_vars/<included in group from hosts> or /etc/ansible/<hostname>
    - name: Update Syslog
      cisco.ios.ios_config:
        src: ../roles/system/templates/syslog.j2
      tags:
        - syslog
