---
- name: Get gather_facts
  cisco.iosxr.iosxr_facts:
    gather_subset:
    - 'config'
- name: Get OS Version
  debug: var=ansible_net_version

#- name: Update NXOS Syslog
#  cisco.nxos.nxos_config:
#    src: syslog-cisco-nxos.j2
#  tags:
#    - syslog
## Update cisco ios-xr devices syslogs (ONLY WORKS ON 5.3 or ABOVE for port).

#- name: Update Syslog
#  cisco.iosxr.iosxr_config:
#    src: syslog-ciscoxr.j2
#  tags:
#    - syslog