---
- name: Gather Interface Info
  hosts: testing-metro-junos
  connection: netconf
#  connection: local
  gather_facts: false
  vars:
#    ansible_user: ansible
#    ansible_ssh_pass: Ansible1
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p {{ jh_ssh_user }}@{{ jh_ssh_host }} -p {{ jh_ssh_port }} -o KexAlgorithms=+diffie-hellman-group1-sha1 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /Ansible/ansible.key"  
    ansible_network_os: junos
    ansible_python_interpreter: /usr/bin/python3
  tasks:
#  - name: Gather junos interfaces as in given arguments
#    junos_rpc:
#      rpc: get-interface-information
  - name: Gather junos interfaces as in given arguments
    junipernetworks.junos.junos_interfaces:
      state: gathered
    register: response

  - name: Display Results
    debug: var=response

#  - name: Write to file
#    local_action: copy content={{response}} dest=./variable.txt

  - name: Run python test
    shell: python3 ./convert-interface.py '{{ response | to_json(ensure_ascii=False) }}' ./exports/{{ ansible_host }}.csv
