---
- hosts: all
  gather_facts: false
  #connection: local
  #connection: netconf
  #connection: network_cli
  vars:
    system:
      settings:
        del_user:
          - user: metsohead
          - user: testing
  tasks:
    - import_role:
        name: add-delete-users